# Import all IAM check functions for easy access
from app.services.recommendation.check.iam.root_account_access_key import check_root_account_access_key
from app.services.recommendation.check.iam.mfa_enabled import check_mfa_enabled
from app.services.recommendation.check.iam.unused_credentials import check_unused_credentials
from app.services.recommendation.check.iam.excessive_permissions import check_excessive_permissions
from app.services.recommendation.check.iam.external_trust_roles import check_external_trust_roles
from app.services.recommendation.check.iam.direct_attached_policies import check_direct_attached_policies
from app.services.recommendation.check.iam.access_key_rotation import check_access_key_rotation
from app.services.recommendation.check.iam.password_policy import check_password_policy
from app.services.recommendation.check.iam.service_linked_roles import check_service_linked_roles